sudo: true
language: cpp
compiler: gcc
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov
  - ./install_oclint.sh

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
  - ./build_black_jack.sh
  - ./build_test.sh
  - ./travis_qmake_gcc_cpp11_boost_test_gcov_oclint_test
  - ./get_code_cov.sh
  - codecov
  - ./build.sh
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
