sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - ./install_oclint.sh

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - cd Assignment3; qmake
  - cd Assignment3; make
  - cd Assignment3; ./assignment3
  - cp get_code_cov.sh Assignment3
  - cd Assignment3; ./get_code_cov.sh
  - cd Assignment3; codecov
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - bash <(curl -s https://codecov.io/bash)
